# スクリプト実行設定
script:
  stream_actual_duration_seconds: 3600 # 実際の配信時間 (秒)例:28800
  obs_stream_start_timeout_seconds: 60 # OBSが配信を開始するまでの待機時間 (秒)

  # ループ設定
  loop:
    count: 3 # 配信を繰り返す回数 (0で無制限)
    duration_hours: 0 # 配信を継続する合計時間 (時間単位, 0で無制限)
    expiration_datetime: "20991231T235959" # 配信を終了する日時 (YYYYMMDDTHHMMSS形式, 例: "20251231T235959", 空文字列で無制限)

# OBS WebSocket設定
obs:
  host: "localhost" # WecSocketのホスト名
  port: 4455 # WecSocketのポート番号
  password: "" # WecSocketのパスワード
  app_path: "/Applications/OBS.app" # macOS用

# OBS実行設定
obs_execution:
  connection_timeout_seconds: 3 # OBSへの接続試行のタイムアウト (秒)
  launch_wait_seconds: 5 # OBS起動後の待機時間 (秒)
  stream_status_polling_interval_seconds: 1 # OBSストリームステータス確認間隔 (秒)
  set_stream_settings_max_retries: 5 # ストリーム設定のリトライ最大回数
  set_stream_settings_retry_delay_seconds: 5 # ストリーム設定のリトライ間隔 (秒)

# YouTubeストリーミング設定
youtube:
  rtmp_url: "rtmp://a.rtmp.youtube.com/live2" # サーバー

  # YouTubeブロードキャスト設定
  broadcast:
    privacy_status: "private" # 公開範囲: 'private' (非公開), 'public' (公開), 'unlisted' (限定公開)
    enable_auto_start: true
    enable_auto_stop: true
    latency_preference: "ultraLow"
    category_id: "15" # カテゴリID (例: "ペットと動物"は15)
    made_for_kids: false # 子供向けではない
    enable_dvr: true # DVRを有効にする
    enable_live_chat: true # ライブチャットを有効にする
    record_from_start: true # 開始時から録画する
    enable_archive: true # アーカイブを有効にする
    is_modified_content: false # 加工されたコンテンツではない

    # YouTube配信のタイトル、説明、タグ、再生リストの設定
    title_format: "{date} {time} #shibainu #柴犬"
    description: "これは自動化されたライブ配信です。"
    tags:
      - "shibainu"
      - "柴犬"
      - "live"
      - "自動配信"
    scheduled_duration_seconds: 28800 # YouTubeに伝える配信の予定時間 (秒)。実際の配信時間は"stream_actual_duration_seconds"になります。
    playlist_title_format: "%Y年%m月" # 例: "2025年08月"

  # YouTubeストリーム設定
  stream:
    format: "1080p"
    ingestion_type: "rtmp"

  # YouTubeクリーンアップ設定
  cleanup_old_broadcasts: false # 新しい配信枠作成時に既存の予定されている配信枠とライブストリームを削除するかどうか

  # YouTube認証設定
  client_secrets_file: "client_secret.json"
  token_pickle_file: "token.pickle"

  # YouTubeプレイリスト設定
  playlist:
    default_privacy_status: "private" # プレイリストのデフォルト公開範囲
    default_language: "ja" # プレイリストのデフォルト言語
    description_format: "{playlist_title} のライブ配信アーカイブ"

  # YouTubeブロードキャスト/ストリーム作成設定
  create:
    start_time_buffer_seconds: 5 # 配信開始予定時刻のバッファ (秒)
    stream_title_format: "Aina-YTLoop Stream - {datetime}" # ストリームのタイトル形式
    stream_frame_rate: "60fps" # ストリームフレームレート
